services:
  api:
    build:
      context: ./api
    volumes:
      - ../../models:/app/models:ro
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/model.pkl
    restart: unless-stopped

  app:
    build:
      context: ./app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
